<a href="https://colab.research.google.com/github/PRANAV40/Python_Program/blob/main/PythonRevision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#A single line that makes your Python code blazingly fast.
from numba import njit

@njit
def function_without_numba():
  result = []
  for a in range(10000):
    for b in range(10000):
      if (a+b)%11 == 0:
        result.append((a,b))
function_without_numba()

In [ ]:
#Find your country on a Map using Python
import plotly.express as px

country = input("Enter you country name here: ")
data = {
    'Country' : [country],
    'Values'  : [100]
}
fig = px.choropleth(
    data,
    locations='Country',
    locationmode='country names',
    color='Values',
    color_continuous_scale='Inferno',
    title=f'Country Map Highlighting(Country)'
)
fig.show()

Enter you country name here: China


In [ ]:
#*args

def numbers_value(*args):
  for arg in args:
    print(arg)

numbers_value(1,2,4,5)

1
2
4
5


In [ ]:
#**kwargs

def numbers_value(**kwargs):
  for key, value in kwargs.items():
    print(f"{key}:{value}")

numbers_value(a=1,b=2,c=4,d=5)

a:1
b:2
c:4
d:5


In [ ]:
def merge_arrays(arrayA, arrayB):
  return sorted(set(arrayA + arrayB))

a = [1,2,3,4,5,6,7,8,9]
b = [1,2,3,4,5,6,7,8,9,10]
c = merge_arrays(a,b)
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
def square_patter(n):
  for i in range(0,n):
    if (i==0 or i == n-1):
      print("X " * n)
    else:
      print("X " + "  " * (n - 2) + "X")
square_patter(5)

X X X X X 
X       X
X       X
X       X
X X X X X 


In [ ]:
def pattern(n):
  for i in range(0,n):
    print("X")
pattern(5)

X
X
X
X
X


In [ ]:
fruits = ['Apple','Banana','Chery','Pears']

for idx, fruit in enumerate(fruits):
  print(f'{idx}. {fruit}')

0. Apple
1. Banana
2. Chery
3. Pears


In [ ]:
fruits = ['Apple','Banana','Chery','Pears']

for idx, fruit in enumerate(fruits):
  print(f'{idx + 1}. {fruit}')

1. Apple
2. Banana
3. Chery
4. Pears


In [ ]:
fruits = ['Apple','Banana','Chery','Pears']

for idx, fruit in enumerate(fruits, start=1):
  print(f'{idx}. {fruit}')

1. Apple
2. Banana
3. Chery
4. Pears


In [ ]:
def pattern(n):
  for row in range(n):
    print(row * " " + n * "* ")
pattern(4)

* * * * 
 * * * * 
  * * * * 
   * * * * 


In [ ]:
number: int = 1000
print(number << 1)
print(number >> 1)
#The princple of this is right to multiply and left to multiply

2000
500


In [ ]:
# Add two numbers
num1 = 40
num2 = 33
print(num1 + num2)

73


In [ ]:
num1 = int(input("Enter 1st number"))
num2 = int(input("Enter 2nd number"))
sum = num1 + num2
print(sum)

Enter 1st number33
Enter 2nd number23
56


In [ ]:
#Square root
num = 49
sr = num**.5
print(sr)

7.0


In [ ]:
# Even or Odd
num = int(input("Enter a num:"))
if num % 2 == 0:
  print("Even")
else:
  print("Odd")

Enter a num:2
Even


In [ ]:
#Leep year logic
year = int(input("Enter year here: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
  print(year,"is leep year")
else:
  print(year,"is not a leep year")

Enter year here: 2021
2021 is not a leep year


In [ ]:
#Area of Trianle
base = float(input("Enter the base of triagle"))
height = float(input("Enter the height of triagle"))

area = (0.5) * base * height
print(area)

Enter the base of triagle12
Enter the height of triagle5
30.0


In [ ]:
# Kilometer to Miles in Python
kilometer = float(input("Enter your kilometer: "))

conversion_factor = 0.621371

miles = kilometer * conversion_factor
print(f"{kilometer} kilometers is equal to {miles:.2f} miles")

Enter your kilometer: 160
160.0 kilometers is equal to 99.42 miles


In [ ]:
# Program to convert Celsius to Fahrenheit
celsius = float(input("Enter your Celsius: "))
fahrenheit = (celsius * 1.8) + 32
print(f"{celsius}°C is equal to {fahrenheit}")

Enter your Celsius: 37.5
37.5°C is equal to 99.5


In [ ]:
import random
num = random.randint(1,10)
print(num)

4


In [ ]:
import random
num = random.random()
print(num)

0.8482105510177349


In [ ]:
#Wrirte a program to reverse a string
def reverse_string(data):
  res = ""
  for char in data:
    res = char + res

  return res

reverse_string(data="level")

'level'

In [ ]:
#Write a program to delete all consonants from string
def return_string(data):
  vowels = 'AEIOUaeiou'
  result = [char for char in data if not char.isalpha() or char in vowels]
  return result

return_string(data="Howareuiam")

['o', 'a', 'e', 'u', 'i', 'a']

In [ ]:
#write a program to find the prime number between 1 to N
def prime_number(num):
  for z in range(2,num):
    if num % z == 0:
      return False
  return True
# num = int(input("Enter you number:"))
# prime_number(num)
def add(number):
  total = 0
  for z in range(2,number + 1):
    if(prime_number(z)):
      total = total + z
  return total
add(number=10) # 2 + 3 + 5 + 11 + 13

17

In [ ]:
lsy = [1,2,4,3,5,1,4,2,7,9,4,6,9]

rmv = set(lsy)
print(list(rmv))

[1, 2, 3, 4, 5, 6, 7, 9]


In [ ]:
dicts = {
    "F_Name" : "Pranav",
    "L_name" : "Mishra",
    "Age" : 24
}
print(dicts)

{'F_Name': 'Pranav', 'L_name': 'Mishra', 'Age': 24}


In [ ]:
def leep_year(year):
  if(year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    return True
  else:
    return False

input_year = int(input("Enter year here:"))

if leep_year(input_year):
  print(f"{input_year} is a leep year")
else:
  print(f"{input_year} is not a leep year")

Enter year here:2020
2020is a leep year


In [ ]:
def reverse_string(strings):
  # return strings[::-1]

  reversestring = ""
  for char in strings:
    reversestring = char + reversestring
  return reversestring

input_string = "Hello World"
reversestrings = reverse_string(input_string)
print("Orignal string: ",input_string)
print("Reverse string: ",reversestrings)

Orignal string:  Hello World
Reverse string:  dlroW olleH


In [ ]:
# is: It is a identity operator and Check memory reference/memor address of two object
# ==: It is comparison operator and Check actual contents/values of two objects.
a = 10
print(id(a))
b = 10
print(id(b))

print(a is b)

134390910321168
134390910321168
True


In [ ]:
ls = [10,20,30]
ls1 = [10,20,30]
print(id(ls))
print(id(ls1))
print(ls is ls1)
print(ls == ls1)

134390601286528
134390601300928
False
True


In [ ]:
from os import PRIO_USER
# Wrte a Python function to move all the even numbers to the front of the list while maintaing their original order.
# The odd numbers should follow in their original order
# original_list = [1,2,3,4,5,6,7,8,9]
# Desired_output = [2,4,6,8,,1,3,5,7,9]

original_list = [1,2,3,4,5,6,7,8,9]
even = []
odd = []
for num in original_list:
  if num %2 == 0:
    even.append(num)
  else:
    odd.append(num)

print(even)
print(odd)
print(even + odd)

[2, 4, 6, 8]
[1, 3, 5, 7, 9]
[2, 4, 6, 8, 1, 3, 5, 7, 9]


In [ ]:
#Solve the above question using function
original_list = [1,2,3,4,5,6,7,8,9]
even = []
odd = []

def solution(data):
  for num in data:
      if num%2 == 0:
        even.append(num)
      else:
        odd.append(num)
  return even + odd
number = solution(original_list)
print("This is solve using function",number)

This is solve using function [2, 4, 6, 8, 1, 3, 5, 7, 9]


In [ ]:
#Solve the above question using List comprehension
original_list = [1,2,3,4,5,6,7,8,9]
def list_solutons(data):
  even = [num for num in data if num%2 == 0]
  odd = [num for num in data if num%2 != 0]
  return even + odd

print("This is solve using List Comprehension:",list_solutons(original_list))

This is solve using List Comprehension: [2, 4, 6, 8, 1, 3, 5, 7, 9]


In [ ]:
# Solve the above question using sorted function
original_list = [1,2,3,4,5,6,7,8,9]
def even_odd(num):
  if num%2 == 0:
    return False
  else:
    return True

print(sorted(original_list,key=even_odd))

# Solve the above question using lambda function

print(sorted(original_list,key=lambda num:num%2 != 0))

[2, 4, 6, 8, 1, 3, 5, 7, 9]
[2, 4, 6, 8, 1, 3, 5, 7, 9]


In [ ]:
# Given list of integers return the maximum value
def find_max(nums):
  max_value = nums[0]
  for i in range(0,len(nums)):
    if nums[i] > max_value:
      max_value = nums[i]

  return max_value

print(find_max([2,4,6,7,8,9,3]))
print(find_max([1,1,1,1]))

9
1


In [ ]:
def triangle(n):
  for i in range(n):
    print(i* " " + n*"* ")

triangle(5)

* * * * * 
 * * * * * 
  * * * * * 
   * * * * * 
    * * * * * 


In [ ]:
10 * " Pranav"

' Pranav Pranav Pranav Pranav Pranav Pranav Pranav Pranav Pranav Pranav'

In [ ]:
print("c:\doc\navin")
print(r"c:\doc\navin")

c:\doc
avin
c:\doc\navin


In [ ]:
# List in Python
nums = [25,12,36,95,13]
nums

[25, 12, 36, 95, 13]

In [ ]:
nums[0]

25

In [ ]:
nums[4]

13

In [ ]:
nums[2:]

[36, 95, 13]

In [ ]:
nums[-1]

13

In [ ]:
nums[-5]

25

In [ ]:
names =["Pranav","Mishra","Ajay"]
names

['Pranav', 'Mishra', 'Ajay']

In [ ]:
values = [9.5,"Navin",24]
values

[9.5, 'Navin', 24]

In [ ]:
mil = [nums,names]
mil

[[25, 12, 36, 95, 13], ['Pranav', 'Mishra', 'Ajay']]

In [ ]:
nums.append(34)
nums

[25, 12, 36, 95, 13, 34]

In [ ]:
nums.insert(2,21)
nums

[25, 12, 21, 36, 95, 13, 34]

In [ ]:
nums.remove(13)
nums

[25, 12, 21, 36, 95, 34]

In [ ]:
nums.pop(1)
nums

[25, 36, 95, 34]

In [ ]:
nums.pop()

34

In [ ]:
del nums[2:]
nums

[25, 36]

In [ ]:
nums.extend([22,32,56,76])
nums

[25, 36, 22, 32, 56, 76]

In [ ]:
min(nums)

22

In [ ]:
max(nums)

76

In [ ]:
sum(nums)

247

In [ ]:
nums.sort()
nums

[22, 25, 32, 36, 56, 76]

In [ ]:
#Tuple and Sets
tup = (21,34,26,27)
tup

(21, 34, 26, 27)

In [ ]:
print(tup[1])

34


In [ ]:
#Set
s = {22,25,14,2,43,56,22}
s

{2, 14, 22, 25, 43, 56}

In [ ]:
# Dictionary in Python
data = {1:'Pranav',2:'Anu',3:'Alok'}
data

{1: 'Pranav', 2: 'Anu', 3: 'Alok'}

In [ ]:
data[3]

'Alok'

In [ ]:
data[1]

'Pranav'

In [ ]:
data.get(2)

'Anu'

In [ ]:
data.get(1,'Not Found')

'Pranav'

In [ ]:
data.get(4,'Not Found')

'Not Found'

In [ ]:
keys = ['Pranav','Aniket','Amit']
values = ['Python','Cloud','Data']
data = dict(zip(keys,values))
data

{'Pranav': 'Python', 'Aniket': 'Cloud', 'Amit': 'Data'}

In [ ]:
data['Kajal'] = 'Web'
data

{'Pranav': 'Python', 'Aniket': 'Cloud', 'Amit': 'Data', 'Kajal': 'Web'}

In [ ]:
del data['Amit']
data

{'Pranav': 'Python', 'Aniket': 'Cloud', 'Kajal': 'Web'}

In [ ]:
#Variable in Python
num = 5
print(id(num))

133238619357552


In [ ]:
name = 'Name'
print(id(name))

133238615958192


In [ ]:
a = 10
b = 10
print(id(a))
print(id(b))
print(id(10))

k = 10
print(id(k))
a = 9
print(id(a))

133238619357712
133238619357712
133238619357712
133238619357712
133238619357680


In [ ]:
PI = 3.14
r = 5
c = PI * r * r
print(c)

78.5


In [ ]:
type(a)

int

In [ ]:
type(PI)

float

In [ ]:
#Data Types in Python
num = 2.5
type(num)

float

In [ ]:
num = 4
type(num)

int

In [ ]:
for i in range(1,10):
  if i % 2 == 0:
    print("Even:",i)

Even: 2
Even: 4
Even: 6
Even: 8


In [ ]:
ss = [1,25,3,4,5,66,25,24,5,66]
print(set(ss))

{1, 66, 3, 4, 5, 24, 25}


In [ ]:
d = {'Pranav':'MI','Aniket':'Samsung','Amit':'OnePlus','Harsh':'Infix'}
print(d)

{'Pranav': 'MI', 'Aniket': 'Samsung', 'Amit': 'OnePlus', 'Harsh': 'Infix'}


In [ ]:
d.keys()

dict_keys(['Pranav', 'Aniket', 'Amit', 'Harsh'])

In [ ]:
d.values()

dict_values(['MI', 'Samsung', 'OnePlus', 'Infix'])

In [ ]:
d.get('Amit')

'OnePlus'

In [ ]:
# Math Functon
import math
x = math.sqrt(25)
print(x)

5.0


In [ ]:
print(math.floor(2.9))
print(math.ceil(2.2))

2
3


In [ ]:
3 ** 2

9

In [ ]:
print(math.pow(3,2))
print(math.pi)
print(math.e)

9.0
3.141592653589793
2.718281828459045


In [ ]:
# Swap two number
num1 = 34
num2 = 24

temp = num1
num1 = num2
num2 = temp
print(num1)
print(num2)

num1 = num1 + num2
num2 = num1 - num2
num1 = num1 - num2
print(num1)
print(num2)

24
34
34
24


In [ ]:
#User input in Python
num1 = int(input("Enter 1st number: "))
num2 = int(input("Enter 2nd number: "))

num3 = num1 * num2
print(f"The multiply of {num1} and {num2} is: ",num3)

Enter 1st number: 20
Enter 2nd number: 2
The multiply of 20 and 2 is:  40


In [ ]:
#Eval functon in input
result = eval(input("Enter the expression: "))
print(result)

Enter the expression: 2 + 5 -1
6


In [ ]:
#While loop Statement
i =1
while i <= 5:
  print("Om")
  i += 1

Om
Om
Om
Om
Om


In [ ]:
# For loop
lst = [1,3.5,7,9,"Pranav"]
for i in lst:
  print(i)

1
3.5
7
9
Pranav


In [ ]:
# Break,Continue and Pass
av = 5
candy_input = int(input("How many candies you want?: "))
i = 1
while i <= candy_input:
  if i>av:
    print("Out of Stock")
    break
  print("Candy")
  i += 1

print("Bye")

How many candies you want?: 7
Candy
Candy
Candy
Candy
Candy
Out of Stock
Bye


In [ ]:
for i in range(1,101):
  if i%3 == 0 and i%5==0:
    continue
  print(i)
print("Bye")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
16
17
18
19
20
21
22
23
24
25
26
27
28
29
31
32
33
34
35
36
37
38
39
40
41
42
43
44
46
47
48
49
50
51
52
53
54
55
56
57
58
59
61
62
63
64
65
66
67
68
69
70
71
72
73
74
76
77
78
79
80
81
82
83
84
85
86
87
88
89
91
92
93
94
95
96
97
98
99
100
Bye


In [ ]:
# Break,Continue and Pass
for i in range(15):
  if i == 5:
    break
  print("Hello",i)

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4


In [ ]:
for i in range(15):
  if i == 5:
    continue
  print("Hello",i)

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4
Hello 6
Hello 7
Hello 8
Hello 9
Hello 10
Hello 11
Hello 12
Hello 13
Hello 14


In [ ]:
#Pass
def fun():
  pass

In [ ]:
# Patterns
def pattern(n):
  for i in range(n):
    for j in range(n):
      print("*",end="")
    print()

pattern(5)

*****
*****
*****
*****
*****


In [ ]:
def patterns(n):
  for i in range(n):
    for j in range(i):
      print("*",end="")
    print()
num = int(input("Enter the number: "))
patterns(num)

Enter the number: 5

*
**
***
****


In [ ]:
#For else
nums = [11,16,23,22,13,52]
for num in nums:
  if num % 5 == 0:
    print(num)
    break
else:
  print("Not Found")

Not Found


In [ ]:
# Prime number
num = int(input("Enter the number: "))
for i in range(2,num):
  if num % i == 0:
    print("Not Prime!")
    break
else:
  print("It's Prime")

Enter the number: 12
Not Prime!


In [ ]:
# Array in Python
from array import *
vals = array('i',[5,7,3,9,1])
print(vals)

array('i', [5, 7, 3, 9, 1])


In [ ]:
vals = array('i',[2,7,3,-9,5])
for i in range(len(vals)):
  print(vals[i])

2
7
3
-9
5


In [ ]:
newArr = array(vals.typecode, (a*a for a in vals))
for e in newArr:
  print(e)

4
49
9
81
25


In [ ]:
#Array values from the user
arr = array('i',[])
n = int(input("Enter the length of the array:"))

for i in range(n):
  num = int(input("Enter the next value in the array:"))
  arr.append(num)

print(arr)

val = int(input("Enter the value for search:"))

k = 0
for e in arr:
  if e==val:
    print(f"The position of value {val} is", k)
    break
  k += 1

Enter the length of the array:5
Enter the next value in the array:23
Enter the next value in the array:21
Enter the next value in the array:7
Enter the next value in the array:43
Enter the next value in the array:22
array('i', [23, 21, 7, 43, 22])
Enter the value for search:7
The position of value 7 is 2


In [ ]:
from re import search
arr = array('i',[])
input_len = int(input("Enter the length of the array:"))

for i in range(input_len):
  input_val = int(input(("Enter the next value in the array:")))
  arr.append(input_val)

print(arr)

search_posi = int(input("Enter the value for search:"))
c = 0
for e in arr:
  if e == search_posi:
    print(f"The position of the value {search_posi} is:",c)
    break
  c += 1

print(arr.index(search_posi))

Enter the length of the array:5
Enter the next value in the array:3
Enter the next value in the array:7
Enter the next value in the array:9
Enter the next value in the array:2
Enter the next value in the array:1
array('i', [3, 7, 9, 2, 1])
Enter the value for search:2
The position of the value 2 is: 3
3


In [ ]:
from numpy import *
arr = arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [ ]:
arr = logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [ ]:
arr = linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [ ]:
arr = ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
#Copying an Array
arr = array([1,2,3,4,5])
arr = arr + 5
print(arr)

[ 6  7  8  9 10]


In [ ]:
arr = array([1,22,3,4,51,6])
print(sort(arr))

[ 1  3  4  6 22 51]


In [ ]:
arr1 = array([12,3,41,61])
print(concatenate([arr1,arr2]))

[ 3 12 41 61  2  3  5  9]


In [ ]:
arr2 = arr1.copy()
arr1[1] = 7
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[12  7 41 61]
[12  7 41 61]
132309445602896
132309446548176


In [ ]:
#Working with matrix
from numpy import *
arr1 = array([[1,2,3,4],[5,6,7,9]])
# print(arr1.dtype)
# print(arr1)
# print(arr1.size)

# arr2 = arr1.flatten()
# print(arr2)

# arr3 = arr2.reshape(2,2,3)
# print(arr3)

# m = matrix(arr1)
m = matrix('1,2,3;4,5,6;7,8,3')
print(m.max())

m1 = matrix('1,2,3;4,5,6;7,8,3')
m2 = matrix('1,12,3;14,5,16;7,8,13')
m3 = m1 * m2
print(m3)

8
[[ 50  46  74]
 [116 121 170]
 [140 148 188]]


In [ ]:
# # Functions
# def greet():
#   print("Hello")
#   print("Good Morning!")

# def add(num1,num2):
#   c = num1 + num2
#   print(c)
# greet()
# add(45,55)

def update(c):
  c = 7
  print(c)
update(34)

7


In [ ]:
#Types of Functon
#positon
def add(a,b):
  c = a + b
  print(c)

add(4,6)

10


In [ ]:
#Argument
def person(name,age):
  print(name)
  print(age)

person('Naman',34)

Naman
34


In [ ]:
def sum(*b):
  c = 0
  for i in b:
    c += i
  print(c)

sum(3,34,45,56)

138


In [ ]:
# *awrgs
def person(name,*data):
  print(name)
  print(data)

person('Naman',23,'Mumbai',74765)

Naman
(23, 'Mumbai', 74765)


In [ ]:
 # **kwags
def person(name,**data):
  print(name)
  # print(data)
  for i ,k in data.items():
    print(i,k)

person('Naman',age=34,city='Mumbai',mob=777549)

Naman
age 34
city Mumbai
mob 777549


In [ ]:
#Global Keyword
a = 10
print(id(a))
def somethings():
  a = 15
  x = globals()['a']
  print(id(x))
  print("in funct",a)

  globals()['a'] = 13
somethings()
print('Outside',a)

134955340120592
134955340120592
in funct 15
Outside 13


In [ ]:
# Pass List to a Function
def even_oddCount(lst):
  even = 0
  odd = 0
  for i in lst:
    if i % 2 == 0:
      even += 1
    else:
      odd += 1
  return even,odd

lst = [20,33,45,46,21,29,56,30,23,50,38,32,39]
even,odd = even_oddCount(lst)
print(f"Even:{even} and Odd:{odd}",)

Even:7 and Odd:6


In [ ]:
#Factorials numbers
def fact(n):
  f = 1
  for i in range(1,n+1):
    f = f * i
  return f

x = 5
result = fact(x)
print(result)

120


In [ ]:
#Recursion
def fact(n):
  if n==0:
    return 1
  return n * fact(n-1)

result = fact(5)
print(result)

120


In [ ]:
#Anonymous Function or Lambda function
n = lambda a : a * a
result = n(5)
print(result)

f = lambda a,b : a*b
result = f(5,6)
print(result)

25
30


In [ ]:
#Filter Map Reduce
# def is_even(n):
#   return n%2==0

# nums = [2,3,4,5,7,8,9,4,1,2,6,8]
# even = list(filter(is_even,nums))
# print(even)

nums = [2,3,4,5,7,8,9,4,1,2,6,8]
even = list(filter(lambda n :n%2==0,nums))
print(even)

[2, 4, 8, 4, 2, 6, 8]


In [ ]:
#Map, filter and reduce in Python

nums = [2,3,4,5,7,8,9,4,1,2,6,8]
even = list(filter(lambda n :n%2==0,nums))
doubles = list(map(lambda n : n*2,even))
print(doubles)


from functools import reduce
sum = reduce(lambda a,b: a + b,doubles)
print(sum)

[4, 8, 16, 8, 4, 12, 16]
68


In [ ]:
# Decorator in Python
def div(a,b):
  print(a/b)

def smart_div(func):
  def inner(a,b):
    if a < b:
      a,b = b,a
    return func(a,b)
  return inner

div = smart_div(div)
div(2,4)

2.0


In [ ]:
#Special Variable __name__
print(__name__)

__main__
